# Generated by Django 5.2.4 on 2025-08-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
